# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  web-api:
    image: hypermsg.scada.webapi
    build:
      context: Backend/HyperMsg.Scada.WebApi/
      dockerfile: ./Dockerfile
      args:
        - configuration=Debug
    ports:
      - 8080:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  identity-app:
    image: hypermsg.scada.identityapp
    build:
      context: Backend/HyperMsg.Scada.IdentityApp/
      dockerfile: ./Dockerfile
      args:
        - configuration=Debug
    ports:
      - 8086:8086
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
