@HyperMsg.Scada.WebApi_HostAddress = http://localhost:8080
@AdminEmail = "admin@mail.com"
@AdminPassword = "Admin123!"

POST {{HyperMsg.Scada.WebApi_HostAddress}}/register
Accept: application/json
Content-Type: application/json

{
  "email": {{AdminEmail}},
  "password": {{AdminPassword}}
}

###

POST {{HyperMsg.Scada.WebApi_HostAddress}}/login
Accept: application/json
Content-Type: application/json

{
  "email": {{AdminEmail}},
  "password": {{AdminPassword}}
}

###

GET {{HyperMsg.Scada.WebApi_HostAddress}}/device
Accept: application/json

###
