@HostAddress = http://localhost:8080
@AdminEmail = "admin@mail.com"
@AdminPassword = "Admin123!"

# @name register

POST {{HostAddress}}/register
Accept: application/json
Content-Type: application/json

{
  "email": {{AdminEmail}},
  "password": {{AdminPassword}}
}

###

# @name login

POST {{HostAddress}}/login
Accept: application/json
Content-Type: application/json

{
  "email": {{AdminEmail}},
  "password": {{AdminPassword}}
}

###

# @name GetDevices

GET {{HostAddress}}/device
Accept: application/json
Authorization: Bearer {{login.response.body.$.accessToken}}

###

# Device Types

# @name CreateDeviceType
POST {{HostAddress}}/devicetype
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.accessToken}}

{
  "name": "Fake sensor",
  "description": "Fake sensor device",
  "metricTemplates": [
    {}
  ],
  "commandTemplates": [
    {}
  ]
}

###